setup mobile first
Izebiafe/Portfolio pull request #1
Opened 2023-07-07 18:16 UTC by Izebiafe

- used correct git workflows
- All linters passed
- used css flex to style html navbar

2023-07-07 18:20 UTC, Shedrack-Sunday requested changes
Hi  @Izebiafe 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🔴 

You have submitted a project, that has a failing linter. Kindly fix this before sending it for review 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-07 18:56 UTC, Strangeal requested changes
Hi @Izebiafe, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights
Well-structured files ✅
Correct use of GitHub Flow ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 18:56 UTC, Strangeal commented on index.html
> +    <h1>My Logo</h1>
- [ ] Great job on implementing the first part of your portfolio as specified in the project requirement! 👏 However, there are some minor issues 🐞 that we need to address some minor issues in order for you to move on to the next milestone. To do that kindly consider the below suggestions:

  - [ ] Kindly consider using an `a` tag for your `logo` instead of an `h1` tag to enhance the accessibility and usability of your website. By using an `a` tag, you can transform your logo into a clickable link, providing users with a clear indication that it leads to a specific destination. Additionally, it is a common practice to make logos clickable, allowing users to easily navigate back to the homepage. Using an `a` tag for your `logo` will improve the overall user experience and align with web development best practices.

2023-07-07 18:56 UTC, Strangeal commented on index.html
> +    </div>
- [ ] I would be more appropriate to use a heading (`hx`) tag instead of an `a` tag for the "LET'S CONNECT" text since it functions as a sub-heading of the main heading. By using a heading tag, you convey the semantic meaning that "LET'S CONNECT" is a sub-heading rather than a clickable link. This will improve the clarity and structure of the HTML document, making it more semantically correct.

2023-07-07 22:15 UTC, franclobo requested changes
Hi @Izebiafe, 

# Required Changes ♻️

![istockphoto-1079018918-612x612](https://github.com/Izebiafe/Portfolio/assets/58642949/50319f90-6879-4901-b7b2-7de054eaea99)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- Best practices of HTML & CSS ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 22:15 UTC, franclobo commented on index.html
> +      <h3 href="#">LET'S CONNECT</h3>
- [ ] The correct way to use the `hx` tag with the `a` tag combined is as follow 👇🏽 

```html
<h3><a href="#">LET'S CONNECT</a></h3>
```

Well done using the `href` attribute because this is a link to the contact form, we are going to use it later.

2023-07-07 22:15 UTC, franclobo commented on assets/css/style.css
> +}
- **[OPTIONAL]** Please use the correct styles like font family, weight, font size, etc to be similar to the Figma template 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://github.com/Izebiafe/Portfolio/assets/58642949/2ed5e975-a378-4928-82bf-fabe9372ed9d) | ![image](https://github.com/Izebiafe/Portfolio/assets/58642949/b8455d6a-3478-4818-8f08-20eb46e84cea) |

2023-07-07 22:15 UTC, franclobo commented on assets/css/style.css
> +}
- **[OPTIONAL]** Please use the correct styles like font family, weight, font size, etc to be similar to the Figma template 👇🏽

| Figma template | Your design |
|---|---|
| ![image](https://github.com/Izebiafe/Portfolio/assets/58642949/c2da1058-f58b-47a0-9dae-7be534f2e49e) | ![image](https://github.com/Izebiafe/Portfolio/assets/58642949/a11a9272-93ea-4f7b-b2b4-410ffcb15161) |

2023-07-07 22:15 UTC, franclobo commented on assets/css/style.css
> +}
- **[OPTIONAL]** Please use the correct styles like font family, weight, font size, etc to be similar to the Figma template 👇🏽

| Figma template | Your design |
|---|---|
| ![image](https://github.com/Izebiafe/Portfolio/assets/58642949/617806de-0ca8-4102-9a1c-fea34ac3237b) | ![image](https://github.com/Izebiafe/Portfolio/assets/58642949/d23af6b5-a8a2-436f-99f7-2e1f5654cfc4) |

2023-07-08 07:28 UTC, levy002 approved these changes
## Hello @Izebiafe  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Highlights
- No linter errors :heavy_check_mark: 
- Implemented all suggested changes :heavy_check_mark: 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 08:14 UTC, merged